include:
  - board: nice_nano_v2
    shield: ao40_left
  - board: nice_nano_v2
    shield: ao40_right
  - board: nice_nano_v2
    shield: ao20_L
  - board: nice_nano_v2
    shield: ao20_R
  - board: nice_nano_v2
    shield: settings_reset